version: 2.1
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  
  configure_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["be:b0:27:ec:37:c1:32:b7:57:4f:29:92:f8:b8:3a:49"]
        - run:
            name: Install dependencies
            command: |
              # install the dependencies needed for your playbook
              apk add --update ansible
#              pip install ansible
              apk update && apk add --no-cache musl-dev libffi-dev openssl-dev make gcc python py2-pip python-dev
              pip install cffi
              pip install ansible
        - run:
            name: Configure server
            command: |
              ansible-playbook main.yml -i inventory.txt
# Sequential workflow
workflows:
  # Name the workflow
  infrastructure:
    jobs:
#     - create_infrastructure
      - configure_infrastructure